export const BRAND = {
  name: 'Bharat Academix',
  tagline: 'Unlock your potential. We\'ll handle the rest.',
  whatsappE164: '+918905483183',
  whatsappDigits: '918905483183',
  email: 'bharatacademix@gmail.com',
} as const

export const COUNTRIES = [
  {
    code: 'IN',
    label: 'India',
    flag: '🇮🇳',
    currency: 'INR',
    tz: 'IST',
    timeZone: 'Asia/Kolkata',
  },
  {
    code: 'US',
    label: 'USA',
    flag: '🇺🇸',
    currency: 'USD',
    tz: 'ET',
    timeZone: 'America/New_York',
  },
  {
    code: 'GB',
    label: 'UK',
    flag: '🇬🇧',
    currency: 'GBP',
    tz: 'GMT/BST',
    timeZone: 'Europe/London',
  },
  {
    code: 'CA',
    label: 'Canada',
    flag: '🇨🇦',
    currency: 'CAD',
    tz: 'ET',
    timeZone: 'America/Toronto',
  },
  {
    code: 'AU',
    label: 'Australia',
    flag: '🇦🇺',
    currency: 'AUD',
    tz: 'AEST/AEDT',
    timeZone: 'Australia/Sydney',
  },
  {
    code: 'SG',
    label: 'Singapore',
    flag: '🇸🇬',
    currency: 'SGD',
    tz: 'SGT',
    timeZone: 'Asia/Singapore',
  },
  {
    code: 'AE',
    label: 'UAE',
    flag: '🇦🇪',
    currency: 'AED',
    tz: 'GST',
    timeZone: 'Asia/Dubai',
  },
  {
    code: 'OTHER',
    label: 'Other',
    flag: '🌍',
    currency: 'USD',
    tz: 'UTC',
    timeZone: 'UTC',
  },
] as const

export type CountryCode = (typeof COUNTRIES)[number]['code']
export type CurrencyCode = (typeof COUNTRIES)[number]['currency']

export const TRUST_STRIP = [
  '✨ Originality-first workflow',
  '⏱️ On-time delivery',
  '🤫 Fully confidential',
  '📄 Editing + formatting included',
  '💻 50+ software domains',
] as const

export const SERVICE_FIELDS = [
  '🎓 Computer Science',
  'IT',
  'Electronics',
  'Electrical',
  'Mechanical',
  'Civil',
  'Chemical',
  'Biotechnology',
  'Biomedical',
  'Aerospace',
  'Agricultural',
  'Marine',
  'Petroleum',
  'Textile',
  'Data Science',
  'AI/ML',
  'Cybersecurity',
  'Cloud Computing',
  'IoT',
  'Robotics',
  'VLSI',
  'Embedded',
  'Physics',
  'Chemistry',
  'Mathematics',
  'Statistics',
  'Biology',
  'Microbiology',
  'Biochemistry',
  'Commerce',
  'Economics',
  'Finance',
  'Marketing',
  'HR',
  'Business Management',
  'Law',
  'Psychology',
  'English',
  'History',
  'Political Science',
  'Sociology',
  'Journalism',
  'Mass Communication',
  'Architecture',
  'Design',
  'Fine Arts',
  'Animation',
  'Multimedia',
  'Pharmacy',
  'Nursing',
] as const

export const PRICING_ROWS = [
  {
    service: 'Minor Project',
    INR: '1,000 - 4,000',
    USD: '80 - 150',
    GBP: '60 - 120',
    CAD: '100 - 180',
    AUD: '120 - 220',
  },
  {
    service: 'Major Project',
    INR: '4,000 - 25,000',
    USD: '200 - 500',
    GBP: '150 - 400',
    CAD: '250 - 600',
    AUD: '300 - 700',
  },
  {
    service: 'Research Paper (UG/PG)',
    INR: '1,500 - 12,000',
    USD: '120 - 250',
    GBP: '90 - 200',
    CAD: '150 - 300',
    AUD: '180 - 350',
  },
  {
    service: 'Research Paper (Phd/Postdoc)',
    INR: '5,000 - 25,000',
    USD: '250 - 500',
    GBP: '200 - 400',
    CAD: '300 - 600',
    AUD: '350 - 650',
  },
  {
    service: 'Thesis Chapter',
    INR: '2,000 - 10,000',
    USD: '180 - 400',
    GBP: '150 - 350',
    CAD: '200 - 500',
    AUD: '220 - 550',
  },
  {
    service: 'Full Thesis (coaching + editing)',
    INR: '2,000 - 1,50,000',
    USD: '800 - 2500',
    GBP: '600 - 2000',
    CAD: '1000 - 3000',
    AUD: '1100 - 3200',
  },
  {
    service: 'Patent Draft (specification support)',
    INR: '2,000 - 50,000',
    USD: '500 - 1200',
    GBP: '400 - 1000',
    CAD: '600 - 1500',
    AUD: '650 - 1600',
  },
  {
    service: 'Assignment (per page — editing/coaching)',
    INR: '150 - 300',
    USD: '5 - 10',
    GBP: '4 - 8',
    CAD: '6 - 12',
    AUD: '7 - 14',
  },
    {
    service: 'Professional PPT',
    INR: '500 - 1000',
    USD: '5 - 10',
    GBP: '4 - 8',
    CAD: '6 - 12',
    AUD: '7 - 14',
  },
] as const

export const SUPPORT_AREAS = [
  {
    title: 'Major/Minor Projects',
    summary: 'Mentoring, architecture planning, and code review. End-to-end guidance from ideation to final submission.',
    image: '/images/majorproject.avif',
    whatsappText: 'I need support for major/minor projects.',
  },
  {
    title: 'Research Papers (UG/PG/Scientific)',
    summary: 'Structure, references, and publication-ready edits. Help with journal selection and response to reviewers.',
    image: '/images/research.jpg',
    whatsappText: 'I need support for research paper writing/editing.',
  },
  {
    title: 'Literature Reviews',
    summary: 'Systematic/scoping/narrative review guidance. Search strategy, synthesis, and PRISMA flow diagrams.',
    image: '/images/literature1.jpg',
    whatsappText: 'I need support for a literature review.',
  },
  {
    title: 'Book Chapters',
    summary: 'Chapter shaping, citations, and publisher formatting. Adherence to Springer, Elsevier, or CRC guidelines.',
    image: '/images/bookchapters1.jpg',
    whatsappText: 'I need support for a book chapter.',
  },
  {
    title: 'Thesis/Dissertation Editing',
    summary: 'Chapter flow, language polish, and formatting. University-specific template and reference management.',
    image: '/images/thesis11.png',
    whatsappText: 'I need support for thesis/dissertation editing.',
  },
  {
    title: 'Project Reports',
    summary: 'Complete report templates, visuals, and references. Executive summary, data presentation, and appendix.',
    image: '/images/project-reports11.jpg', 
    whatsappText: 'I need support for a project report.',
  },
  {
    title: 'Patent Documentation Support',
    summary: 'Drafting support for provisional/complete specs. Claims, drawings, and prior art search assistance. Also includes formality checks, response drafting for office actions, and IP strategy advice. Plus inventor interviews, patent landscape analysis, and commercialization roadmap support.',
    image: '/images/patent1.jpg',
    whatsappText: 'I need support for patent documentation.',
  },
  {
    title: 'PPTs & Viva Decks',
    summary: 'Clear slides, story flow, and delivery notes. Q&A prep and mock viva presentation support.',
    image: '/images/ppt1.png',
    whatsappText: 'I need support for PPT/viva preparation.',
  },
  {
    title: 'Software Projects (All Departments)',
    summary: 'Working builds, demos, and documentation support. Code review, deployment help, and user manuals.',
    image: '/images/software1.jpg',
    whatsappText: 'I need support for a software project.',
  },
] as const

